### ISSUE TITLE
Catch data format issues in sea()?

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#112]
Currently there is no catch if a user inputs data in an unexpected format to sea().

For example, if x is a tree-ring reconstruction with two columns "Year" and "Recon", and with normally ascending row names, the function will log an error code pointing to line 177 in sea.R.

The x variable needs to have row names as years that match those in the event list.

Also, if a user provides a data.frame for event, sea will not function. The event variable needs to be either a vector or an fhx object with a single series. 

Should catch functions be included to either adjust for these inputs or flag them meaningfully for the user?

**Comment by brews** [comment]
Yes. We should be careful about this. Maybe add code to catch the worse-cases of bad formatting. Also might be good to be more explicit about this in the documentation.
