### ISSUE TITLE
Add new dormant fire scar factors

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#115]
Increasingly, we're realizing that the generic D for dormant_fs is not adequate in systems wit fall dormant scars, or where we want to differentiate fall from spring season dormant scars. Importantly, in the Northern Hemisphere this changes the year of the fire,and has meaningful ecological ramifications everywhere.

The FHX codes are F for fall dormant, and S for spring dormant. Need to add these t the levels recognized by burnr.

**Comment by brews** [comment]
Sorry for the delay to reply, been at AGU.

General question for @chguiterman, how likely is it that we're going to have more of these unique seasons pop up? I *think* we'd have to change some seasonal calculations and aggregations... 

Thinking long term: is there any point in generalizing this to the point were people can just define their own symbols or would that be too generalized?

**Comment by brews** [comment]
Idea: We would need to have R spit out a `warning` if a user write an FHX object to an FHX file with these new seasons. The warning would need to explain how the file might not be compatible with other fire history software.

**Comment by petebrew** [comment]
Just to chip in here... adding bespoke event designations makes me terribly sad.  Tinkering with file formats to work around deficiencies is why the Tucson format is so fubar.  There are dozens of reasons why the FHX format is not good enough, that's why we had the PAGES meeting back in August to discuss ways forward.  Forking the FHX format is definitely not the way forward in my opinion!

**Comment by brews** [comment]
New seasons to consider:
- Fall dormant: F, falldormant_fs
- Spring dormant: S, springdormant_fs
- Transition: T, transition_fs
- Early latewood: Y, earlylw_fs 
- Late latewood: W, latelw_fs

**Comment by brews** [comment]
Closing this for now due to lack of interest.
