### ISSUE TITLE
Add labels of actual years of events to the rug at the bottom of plots.

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#13]
Can we include some way to annotate or put the actual year of events in the FHX plot's rug? Bonus points if we can do this without overlapping.

**Comment by brews** [comment]
[ggrepel](https://cran.r-project.org/web/packages/ggrepel/index.html) or [gghighlight](https://cran.r-project.org/web/packages/gghighlight/index.html) might be good tools for this.

**Comment by chguiterman** [comment]
see https://github.com/chguiterman/burnr_demo/blob/master/R/2_graphics.R

**Comment by brews** [comment]
Closing this for now, I guess. Please create a new issue if further work is needed.
