### ISSUE TITLE
Centralize `rec_type` levels, especially for intra-ring positions

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#136]
Across a bunch of functions (eg., `read_fhx` and `composite`) the levels of `rec_type` are listed in the function itself. This means that when/if we update and expand on the levels of `rec_type` to include new intra-ring positions (e.g., https://is.gd/uzrkwp) the updates will have to be made on each function separately. 

Is there a way to centralize these attributes so that each function calls a single list object?

**Comment by brews** [comment]
Yeah, I actually have this on my todo for the next release. I guess I didn't have an issue for this. 

The holdup is that I need it to be immutable so users don't accidentally wipe the list or modify it. I'm a little fuzzy on how to get this in R but I'm working on it.

**Comment by chguiterman** [comment]
This looks slick. Nice job!
