### ISSUE TITLE
Output for `site_stats()` is screwed up

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#138]
Looks like the output for `site_stats()` is screwed up. This is clearly wrong and in need of a fix.

**Comment by brews** [comment]
I've opted to remove `site_stats()` altogether in the upcoming release. You can get the same statistics by defining a printing (via `print()`) on an `intervals()` object. This gives users the most power to define intervals and composites exactly how they like.

Let me know if it creates problems for anyone.

**Comment by chguiterman** [comment]
Good call -- `site_stats` was a precursor to `intervals` and was destined for removal.
