### ISSUE TITLE
Update NEWS.md

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#163]
NEWS.md needs to be cleaned and updated following the changes from PR #162.

We should also call out specific contributers, PRs and Issues in our point-by-point list of changes. I think it's important that we acknowledge contributors as much as we can.

**Comment by chguiterman** [comment]
What's a good format for acknowledging contributors?

**Comment by brews** [comment]
@chguiterman That's a great question. In the NEWS and the release notes, we could do something like:

```
* Addded super cool new DOI badge to README (PR #162, @chguiterman)
```

So, we're mentioning any specific PRs, issues, and calling out the person's name.

PS. I've assigned this issue to myself, because I don't want to forget it but if you're hot to take it on, go ahead and reassign it to yourself, @chguiterman.
