### ISSUE TITLE
get_year() can't handle `<` or `>` operators

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#169]
```
> pgm_early <- get_year(pgm, < 1900)
Error: unexpected '<' in "pgm_early <- get_year(pgm, <"
```

**Comment by brews** [comment]
Yeah, this is documented. It can only take numeric, and vector input. You could pass in a vector of years, as a work-around, getting the min and max years with `year_range()`.

**Comment by brews** [comment]
Closing, unless you have other ideas!

**Comment by chguiterman** [comment]
I messed around with it for a few minutes, and decided it was best to keep the function as is, but add a "Not Run" example to describe how that works. See https://github.com/chguiterman/burnr/commit/642859070b13bdf37c7f4c890e34a58a5f8ad44d
This will be included in my next PR. Doesn't seem like enough for its own PR.

**Comment by brews** [comment]
@chguiterman That's a great idea! I think an example in docs is a really good way to handle this.
