### ISSUE TITLE
Swap failing Travis CI for Github Actions

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#171]
Our CI is no longer working. Travis CI has bitten the dust in the past year and we're switching over to Github Actions to fill the Travis-shaped hole in our hearts.

We need testing. It would be great if we could get it to run on the various R releases for MacOS and Linux, like Travis did.

There is some urgency for this as we have no auto-scheduled testing and major R releases underway.

**Comment by brews** [comment]
There are plenty of resources on this - we're not the only ones making this transition. See https://deanattali.com/blog/migrating-travis-to-github/.

**Comment by chguiterman** [comment]
Good thinking @brews. I just did this for `{dfoliatR}` following the link you provided. It's easy.

**Comment by brews** [comment]
@chguiterman It looks like you're working on this on your fork. Is this something you're thinking of merging in here? This fix for CI/CD is something that merits it's own PR, if you're ready for it now.

**Comment by brews** [comment]
Ahhh, I see it in the new PR (#173). I'm going to edit the PR to reference this issue. 👍
