### ISSUE TITLE
sort() not working on R v 4.0.3

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#172]
Thanks to Mannie Lopez (USGS) for pointing out that sort() appears to have no effect anymore
I thought it was because base R now seems to take over when functions are conflicted, but when `burnr::sort()` or `burnr::sort.fhx()` are specified, an error is triggered
```{r}
Error: 'sort' is not an exported object from 'namespace:burnr'
# and
Error: 'sort.fhx' is not an exported object from 'namespace:burnr'
```

Also, using `burnr:::sort.fhx()` resulted in no error, there was also no affect.

**Comment by chguiterman** [comment]
Update: `sort.fhx()` is working fine. The problem appears to be related to `plot_demograph()`, and then only in R4.0+ and ggplot2_3.3.2

Still investigating.

**Comment by brews** [comment]
Cool, thanks for the update. Looks like you might have a fix ready to merge in, @chguiterman ?
