### ISSUE TITLE
CRAN submission for package burnr_0.6.0.tar.gz does not pass the incoming checks automatically

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#179]
CRAN is bouncing our package release because of an issue with one of the vignettes. This vignette passed local and CI/CD check but is failing on the CRAN win_devel check.

Specifically, it looks like the issue is with the `facet_comps.Rmd` vignette pulling in remote data from from the NOAA server.
```
* checking re-building of vignette outputs ... [8s] WARNING
Error(s) in re-building vignettes:
--- re-building 'facet_comps.Rmd' using rmarkdown
Quitting from lines 24-31 (facet_comps.Rmd) 
Error: processing vignette 'facet_comps.Rmd' failed with diagnostics:
cannot open the connection
--- failed re-building 'facet_comps.Rmd'

--- re-building 'introduction.Rmd' using rmarkdown
--- finished re-building 'introduction.Rmd'

SUMMARY: processing the following file failed:
  'facet_comps.Rmd'

Error: Vignette re-building failed.
Execution halted
```

You can check/replicate this by running `devtools::check_win_devel()` from the root of the package directory. It replicates the error.

Full output from the automated check is:
```
* using log directory 'd:/RCompile/CRANincoming/R-devel/burnr.Rcheck'
* using R Under development (unstable) (2021-02-20 r80030)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'burnr/DESCRIPTION' ... OK
* this is package 'burnr' version '0.6.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... Note_to_CRAN_maintainers
Maintainer: 'Steven Malevich <sbmalev@gmail.com>'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'burnr' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [8s] OK
* checking Rd files ... [1s] OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking R/sysdata.rda ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [7s] OK
** running examples for arch 'x64' ... [8s] OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ... [9s] OK
  Running 'testthat.R' [8s]
** running tests for arch 'x64' ... [10s] OK
  Running 'testthat.R' [9s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [8s] WARNING
Error(s) in re-building vignettes:
--- re-building 'facet_comps.Rmd' using rmarkdown
Quitting from lines 24-31 (facet_comps.Rmd) 
Error: processing vignette 'facet_comps.Rmd' failed with diagnostics:
cannot open the connection
--- failed re-building 'facet_comps.Rmd'

--- re-building 'introduction.Rmd' using rmarkdown
--- finished re-building 'introduction.Rmd'

SUMMARY: processing the following file failed:
  'facet_comps.Rmd'

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 WARNING
```

**Comment by brews** [comment]
Thinking out loud:
Sounds like the container used for running this check might not have internet access? Maybe, maybe not.

Solution would be to move the required data into the package (with correct documentation and citation) so we don't need to pull it from a remote server. Alternatively, we could run the vignette example using data already included in the package.

FI like that we're showing how to pull the remote data as part of the example, but maybe we don't actually execute this bit.

**Comment by brews** [comment]
@chguiterman, do you have time this week to take a swing at this?

If you can get me a PR with a fix, I can rebase my release stuff onto this and attempt a submission to CRAN.

**Comment by chguiterman** [comment]
@brews thanks for finding this -- side Q, do our internal RMD and GitHub Actions checks ignore vignettes? Wondering why we didn't pick this up prior to a CRAN submission. For one, I hate to waist their time, but maybe the bots found this first?

At any rate, yes, I can take care of this. I would like to include the three files in the package, and will comment out the script so that we can still show folks how to gather sites 'in the wild'. 

Thoughts?

**Comment by brews** [comment]
@chguiterman Yeah, we check vignettes. For e.g. see here: https://github.com/ltrr-arizona-edu/burnr/runs/1992049074?check_suite_focus=true#step:9:91. This is the vignette rebuild from the latest check running R devel on Ubuntu 20.04. Seems to run fine.

I've also checked this locally. The code works, and it doesn't take a long time to run (so, I don't think the connection is timing out).

It feels like their winbuild doesn't allow external connections when rebuilding vignettes, but that's just speculation on my part.

Thanks for the help!

**Comment by chguiterman** [comment]
I wonder how the packages that pull from online repositories and databases work their vignettes? 
I'll look into it and patch this up later this week.

**Comment by chguiterman** [comment]
Hopefully the above-referenced commits solve this. My first go was to add the three sites to burnr, but the vignette would not knit because of some backlog loop between the package build and the internal data. The solution was to follow [this vignette from tidyr](https://github.com/tidyverse/tidyr/blob/master/vignettes/tidy-data.Rmd) that puts the data into the `vignettes/` folder. It seems to work. In the future we may be able to call the data directly with `data()`.
