### ISSUE TITLE
DOI for each release, documentation

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#181]
We have a DOI badge but it's not kept up with the most recent releases of burnr.

It would be great if we could backfill the DOIs up through the past releases to the present release.

Need to ensure the README badge updates to point to the most recent releases.

Need to document how to get an updated DOI on releases - include this in HOW_TO_RELEASE in the wiki.

**Comment by chguiterman** [comment]
There's an "all-release" DOI tag/url from Zenodo that we can apply in the README. It will remain in the pkgdown site as well: <https://zenodo.org/record/1134832#.YEoSj2g3mUk> I'll add this the README in my repo for my next PR

But importantly, the Zenodo site is way back logged, maybe that's what you're referring to? I can't recall how to push to it, I think it may be automated, but apparently not, or that needs to be set up? I did it for {dfoliatR} but can't remember the details.

**Comment by brews** [comment]
Note, this is related to an update in PR #182.

**Comment by brews** [comment]
I'm also removing the milestone on this because the README DOI is up to date. Nothing more should need to change for future releases.

**Comment by brews** [comment]
Closing this.
