### ISSUE TITLE
Need a more informed `check_duplicates()` for the `+` operator

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#186]
When checking for duplicates between FHX objects, the current method doesn't get at what we really want to check, which is whether there are duplicates series names. Having two series of the same name, or having the same series in two objects being joined would cause various errors in statistics (psuedoreplication) and interpretation. This is the current error message, which is difficult for users to interpret

``` r
library(burnr)

data("pgm")

pgm2 <- pgm + pgm
#> Error in check_duplicates(f): c(1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 
#> 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 
# an so on...
```
<sup>Created on 2021-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Each row represents the years from a duplicate series, but there's no way to track down the actual duplicates from this message

**Comment by brews** [comment]
Hey @chguiterman! Do you have a PR with a good general fix for this?

I have some time to polish things and I need to get a patch out to the package for CRAN next week and I wanted to see if this was low hanging fruit or maybe something that you've already taken care of?
