### ISSUE TITLE
Intervals() output for Weibull percentiles mislabeled

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#202]
We accidentally swapped the quantiles in `print.intervals()` on the file "intervals.R" and the 0.875 quantile is wrong.

Line 286 reads: `quants <- quantile(x, q = c(0.847, 0.5, 0.125))`

It should read: `quants <- quantile(x, q = c(0.125, 0.5, 0.875))`

**Comment by brews** [comment]
Cool. Good find!

**Comment by chguiterman** [comment]
and while we're at it...are we sure that 0.847 is right? Should it really be 0.875? That would give us the inner seventy-fifth percentile of intervals. I think maybe FHAES uses the 95-th percentile (0.25, 0.975) but can't be sure: https://help.fhaes.org/ pg. 28

**Comment by brews** [comment]
Yeah, I think you're right, @chguiterman. That's a good catch. I changed the order of `q` [in this commit](https://github.com/ltrr-arizona-edu/burnr/commit/f7eaf1225118d163185d0f9221b4f2519753cccb) and "0.847" might be a typo from [this commit](https://github.com/ltrr-arizona-edu/burnr/commit/5e92f2e65797043c1d456b6e2d0e4c47acf82d28). The `quantile()` function works properly on interval objects, but the values in `print()` for intervals are definitely mislabeled. This needs to get fixed.

Would we have shifted the order of `q` to mimic the order or output of another program? I have a vague memory of us considering what people might already be used to. Our original choice of the inner 75%, again, feels like something we deliberately choose to match earlier tools...?

**Comment by chguiterman** [comment]
OK @brews I follow now. Yes, I think this was a mix-up that is easy to correct. I noticed the `quantiles()` function working properly, but we should have these values printed correctly too. Yes, these values match both FHAES and FHX2 -- that's what we were going for back in the days of 2017. See [this PR](https://github.com/ltrr-arizona-edu/burnr/pull/203) to fix the issue
Thanks!

**Comment by brews** [comment]
Updated the description above so it describes all the problems.
