### ISSUE TITLE
Filter by min number of trees scarred

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#68]
This was an idea from a user:

> It hit me the other day that our composite replicates FHAES, by design, but that misses a critical filter option that we used a lot with FHX2 - to filter by 2 or more scared trees.
> 
> I don't know why/how FHAES missed this one, but we shouldn't make the same mistake. 
> 
> Right now, we can filter by a min of 2 trees recording and/or x% scarred. Several papers filter by a min 2 trees scarred or x%. I used this technique in my Siberia work - it gives you replicated fire dates, eliminating single-tree fires and/or some uncertainty.

**Comment by petebrew** [comment]
Erm... this isn't true regarding FHAES.  You *can* filter by 'number of trees recording fire'.

**Comment by brews** [comment]
I will pass this info on to Mr. Guiterman!
