### ISSUE TITLE
Missed recording gaps in plot

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#78]
In the rare case that a series begins, ends and begins to record again, this is not apparent in plot()
When a series ends recording before the end of the series, this is apparent in plot.

**Comment by chguiterman** [comment]
Relevant file: Dumby.fhx (https://www.dropbox.com/s/hvz8a4m6iz6cyzr/Dumby.fhx?dl=0)
Note case 1 above in ABC-07; and case 2 in ABC-06.

**Comment by brews** [comment]
Yes! Yes. Yes. This is a known issue but I've never actually seen a real, live file that had this problem.

**Comment by chguiterman** [comment]
Thanks to the Dumby site, anything is possible.

**Comment by brews** [comment]
Good old Dumby. Have you ever actually run into this problem IRL?

**Comment by chguiterman** [comment]
Yes I have, maybe once or twice. I think it's pretty rare. You might have
two samples of the same tree with separated inner and outer dates and no
overlap. Or you might have a sample that got burned out in a recent fire
that destroyed evidence to one part of the sample but not the whole.

--
Christopher Guiterman, Ph.D.
Research Associate
Laboratory of Tree-Ring Research
University of Arizona

On Tue, Mar 7, 2017 at 10:55 AM, Brewster Malevich <notifications@github.com
