### ISSUE TITLE
Vignettes in help file

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#79]
Get it so that vignettes show up in the R Studio help file menu.

**Comment by brews** [comment]
I'm closing this.

It looks like this is a product of building the package using `devtools::install_github()`. This function does not build vignettes by default. We need to explicitly pass the argument `build_vignettes = TRUE`. You can then check that the vignettes were properly put together with `browseVignettes()` or `browseVignettes('burnr')`.
