### ISSUE TITLE
Put .Deprecated() warning on `mean_interval()` function in stats.R

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#86]
Put .Deprecated() warning on `mean_interval()` function in stats.R.

Should use Intervals() and then mean() on the resulting object.

**Comment by brews** [comment]
Keep in mind that this is used for `series_stats()`. Going to need to code around that.

**Comment by brews** [comment]
Should check that `mean(intervals(composite(x)))` is synonymous with `mean_interval(x)`. Maybe call this function `estimate_mean_interval()` instead?

**Comment by chguiterman** [comment]
it is. The latter is rounded.

--
Christopher Guiterman, Ph.D.
Research Associate
Laboratory of Tree-Ring Research
University of Arizona

**Comment by brews** [comment]
We can ditch `mean_interval()` and just use `mean(interval(x))`, where `x` is a single series fhx object.

**Comment by brews** [comment]
After playing with this for a bit, I've renamed `mean_interval()` to `series_mean_interval()` in 3139199. I hope that this avoid some confusion.

I did not remove `mean_interval()` completely because there were some issues replacing it in `series_stats()`. (lapply passes the series in as a dataframe and not a proper `fhx` object).
