### ISSUE TITLE
Write `count_event_position()` for utils.R

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/burnr#89]
Write `count_event_position()` for utils.R.

See if we can't get 

1. Pretty printing output

2. Sums or counts for standardized seasons? Need to check with @chguiterman on this.

**Comment by chguiterman** [comment]
Seasons to include could be dormant, early earlywood, middle earlywood (ie.
mainly pre-monsoon), and late earlywood, latewood (ie. monsoon season).
Southwest focused I know...

--
Christopher Guiterman, Ph.D.
Research Associate
Laboratory of Tree-Ring Research
University of Arizona

**Comment by brews** [comment]
I've finished a basic implementation for this with a9330b2. This doesn't give default seasons or groups but the user has the option of getting counts from custom, user-defined groups.

For e.g.
```R
grplist <- list(foo = c("dormant_fs", "early_fs"), bar = c("middle_fs", "late_fs"))
count_event_position(pgm, groupby = grplist)
```
